#!/bin/bash

function daedalus-cli-init() {

  UNAME=$(uname -s)
  case "${UNAME}" in
    Darwin*)
      daedalus-cli-init-darwin
      OS=darwin
    ;;
    Linux*)
      daedalus-cli-init-linux  
      OS=linux
    ;;
  esac

}

function daedalus-cli-init-darwin() {

  export CARDANO_NODE_SOCKET_PATH=$(ps ax | grep -v grep | grep 'cardano-node.run.*socket' | sed -e 's|.*\(--socket-path\) \(.*cardano-node.socket\) --.*|\2|g')
  export CARDANO_NODE_PORT=$(pgrep -fl cardano-node.run | sed 's|\(.*\)--port \(.*\) --\(.*\)|\2|g')
  if [ ! -z "$(pgrep -fl 'cardano-wallet.*tls' | grep -i flight)" ]
  then
    WORKING_DIR="Flight"
  else
    WORKING_DIR="Mainnet"
  fi

  PATH=${PATH}:"/Applications/Daedalus ${WORKING_DIR}.app/Contents/MacOS"

}

function daedalus-cli-init-linux() {

  # Get cardano-node's socket file
  export CARDANO_NODE_SOCKET_PATH=$(pgrep -fa cardano-wallet.*tls | sed -e 's|.*\(--node-socket\) \(.*cardano-node.socket\).*|\2|g')
  export CARDANO_NODE_PORT=$(pgrep -fa cardano-node.run | sed 's|\(.*\)--port \(.*\) --\(.*\)|\2|g')

  # Make Daedalus' binaries available to our shell
  CARDANO_BRIDGE_NIX_STORE_BINDIR="~/.daedalus/$(dirname $(lsof -np $(pgrep -af cardano-wallet.*tls | grep -v "grep" | awk '{print $1}') 2>/dev/null | grep bin.cardano-wallet | awk '{print $NF}' | sed -e 's|\(^/tmp.*\)/\(nix.*\)|\2|'))"
  PATH=${PATH}:${CARDANO_BRIDGE_NIX_STORE_BINDIR}

}

function daedalus-cli-run-cardano-wallet() {

  daedalus-cli-init
  case "${OS}" in
    darwin)
      if [ ! -z $(pgrep -fl 'cardano-wallet.*tls' | grep testnet) ]
      then
        cardano-wallet serve \
          --testnet \
          --shutdown-handler \
          --database "${HOME}/Library/Application Support/Daedalus Testnet/wallets" \
          --node-socket "${HOME}/Library/Application Support/Daedalus Testnet/cardano-node.socket"
      else
        cardano-wallet serve \
          --mainnet \
          --shutdown-handler \
          --database "${HOME}/Library/Application Support/Daedalus ${WORKING_DIR}/wallets" \
          --node-socket "${HOME}/Library/Application Support/Daedalus ${WORKING_DIR}/cardano-node.socket"
      fi
    ;;
    linux)
      $(pgrep -fa cardano-wallet.*tls | sed -e 's|--shutdown.*--database|--database|' -e 's|--tls.*metadata.*.iohk.io||' -e 's|^\([0-9]\+\) ||' -e "s|/nix/store|$HOME/.daedalus/nix/store|")
    ;;
  esac


}

# FIXME: cardano-node: fdType: unsupported operation (unknown file type)
#function daedalus-cli-run-cardano-node() {
#
#  daedalus-cli-init
#
#  $(pgrep -a cardano-node | sed -e 's|^\([0-9]\+\) ||' -e "s|/nix/store|$HOME/.daedalus/nix/store|g" -e "s|--database-path chain|--database-path $(dirname $CARDANO_NODE_SOCKET_PATH)/chain|")
#  
#
#}
