#!/bin/bash

function daedalus-cli-init() {

  UNAME=$(uname -s)
  case "${UNAME}" in
    Darwin*)
      daedalus-cli-init-darwin
    ;;
    Linux*)
      daedalus-cli-init-linux  
    ;;
  esac

}

function daedalus-cli-init-darwin() {

  CARDANO_NODE_SOCKET_PATH=$(ps ax | grep -v grep | grep cardano-node.run.*socket | sed -e 's|.*\(--socket-path\) \(.*cardano-node.socket\) --.*|\2|g')
  PATH=${PATH}:"/Applications/Daedalus Mainnet.app/Contents/MacOS"

}

function daedalus-cli-init-linux() {

  # Get cardano-node's socket file
  export CARDANO_NODE_SOCKET_PATH=$(pgrep -fa cardano-wallet.*tls | sed -e 's|.*\(--node-socket\) \(.*cardano-node.socket\).*|\2|g')

  # Make Daedalus' binaries available to our shell
  CARDANO_BRIDGE_NIX_STORE_BINDIR="~/.daedalus/$(dirname $(lsof -np $(pgrep -af cardano-wallet | grep -v "grep\|tls" | awk '{print $1}') 2>/dev/null | grep bin.cardano-wallet | awk '{print $NF}' | sed -e 's|\(^/tmp.*\)/\(nix.*\)|\2|'))"
  PATH=${PATH}:${CARDANO_BRIDGE_NIX_STORE_BINDIR}

}

function daedalus-cli-run-cardano-wallet() {

  daedalus-cli-init
  $(pgrep -a cardano-wallet | sed -e 's|--shutdown.*--database|--database|' -e 's|--tls.*metadata||' -e 's|^\([0-9]\+\) ||' -e "s|/nix/store|$HOME/.daedalus/nix/store|")

}

# FIXME: cardano-node: fdType: unsupported operation (unknown file type)
#function daedalus-cli-run-cardano-node() {
#
#  daedalus-cli-init
#
#  $(pgrep -a cardano-node | sed -e 's|^\([0-9]\+\) ||' -e "s|/nix/store|$HOME/.daedalus/nix/store|g" -e "s|--database-path chain|--database-path $(dirname $CARDANO_NODE_SOCKET_PATH)/chain|")
#  
#
#}
