#!/bin/bash

function daedalus-cli-get-wallet-id() {

  daedalus-cli-init
  WALLET_NAME=$1
  WALLET_ID=$(cardano-wallet wallet list 2>/dev/null | jq -r --arg name ${WALLET_NAME} '.[] | select(.name==$name) | .id')

  echo $WALLET_ID

}

function daedalus-cli-send-tx() {

  daedalus-cli-init
  WALLET_NAME="$1" # must match Daedalus' name in case sensitive
  TX_AMOUNT="$2" # in lovelaces, 1000000 = 1ADA
  TX_DEST_ADDRESS="$3"

  WALLET_ID=$(daedalus-cli-get-wallet-id ${WALLET_NAME})
  
  cardano-wallet transaction create \
    ${WALLET_ID} \
    --payment ${TX_AMOUNT}@${TX_DEST_ADDRESS}

}

# https://github.com/input-output-hk/cardano-wallet/wiki/TxMetadata#examples
function daedalus-cli-send-tx-with-metadata-string() {

  daedalus-cli-init
  WALLET_NAME="$1" # must match Daedalus' name in case sensitive
  TX_AMOUNT="$2" # in lovelaces, 1000000 = 1ADA
  TX_DEST_ADDRESS="$3"
  TX_META_STRING=$(echo $@ | sed "s|$1 $2 $3 ||")
  TX_META_KEY=1337

  WALLET_ID=$(daedalus-cli-get-wallet-id ${WALLET_NAME})

  # If string is longer than 64 bytes limit send an array of strings!
  if [ $(echo ${TX_META_STRING} | wc -c) -lt 64 ]
  then
    cardano-wallet transaction create \
     ${WALLET_ID} \
     --payment ${TX_AMOUNT}@${TX_DEST_ADDRESS} \
     --metadata "{ \"${TX_META_KEY}\":{ \"string\":\"${TX_META_STRING}\" } }"
  else
    SPLIT_TX_META_STRING=$(echo ${TX_META_STRING} | awk '{gsub(/.{63}/,"&\n")}1' | jq -rcRs 'split("\n") | del(.[] |  select(. == "")) | map(split(":")|{string:.[0]}?)')
    cardano-wallet transaction create \
      ${WALLET_ID} \
      --payment ${TX_AMOUNT}@${TX_DEST_ADDRESS} \
      --metadata "{ \"${TX_META_KEY}\":{ \"list\":${SPLIT_TX_META_STRING} } }"
  fi

}

function daedalus-cli-send-tx-with-metadata-from-text-file() {

  daedalus-cli-init
  WALLET_NAME="$1" # must match Daedalus' name in case sensitive
  TX_AMOUNT="$2" # in lovelaces, 1000000 = 1ADA
  TX_DEST_ADDRESS="$3"
  TX_META_TEXT_FILE=$(echo $@ | sed "s|$1 $2 $3 ||")
  TX_META_KEY=1337

  WALLET_ID=$(daedalus-cli-get-wallet-id ${WALLET_NAME})

  SPLIT_TX_META_STRING=$(cat "${TX_META_TEXT_FILE}" | awk '{gsub(/.{63}/,"&\n")}1' | jq -rcRs 'split("\n") | del(.[] |  select(. == "")) | map(split(":")|{string:.[0]}?)')

  cardano-wallet transaction create \
    ${WALLET_ID} \
    --payment ${TX_AMOUNT}@${TX_DEST_ADDRESS} \
    --metadata "{ \"${TX_META_KEY}\":{ \"list\":${SPLIT_TX_META_STRING} } }"

}
